--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 17.2

-- Started on 2025-04-22 18:45:55

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 23 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3845 (class 0 OID 0)
-- Dependencies: 23
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 281 (class 1259 OID 18293)
-- Name: entrenador; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.entrenador (
    equipo_id bigint,
    id bigint NOT NULL,
    especialidad character varying(255),
    nombre character varying(255)
);


ALTER TABLE public.entrenador OWNER TO postgres;

--
-- TOC entry 280 (class 1259 OID 18292)
-- Name: entrenador_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.entrenador ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entrenador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 283 (class 1259 OID 18301)
-- Name: equipo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.equipo (
    fundacion date,
    id bigint NOT NULL,
    ciudad character varying(255),
    nombre character varying(255)
);


ALTER TABLE public.equipo OWNER TO postgres;

--
-- TOC entry 282 (class 1259 OID 18300)
-- Name: equipo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.equipo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 285 (class 1259 OID 18309)
-- Name: estadisticas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.estadisticas (
    asistencias integer NOT NULL,
    goles integer NOT NULL,
    minutos_jugados integer NOT NULL,
    tarjetas_amarillas integer NOT NULL,
    tarjetas_rojas integer NOT NULL,
    id bigint NOT NULL,
    id_jugador bigint NOT NULL,
    id_partido bigint NOT NULL
);


ALTER TABLE public.estadisticas OWNER TO postgres;

--
-- TOC entry 284 (class 1259 OID 18308)
-- Name: estadisticas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.estadisticas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estadisticas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 287 (class 1259 OID 18315)
-- Name: jugador; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jugador (
    dorsal integer NOT NULL,
    fecha_nac date,
    equipo_id bigint NOT NULL,
    id bigint NOT NULL,
    nacionalidad character varying(255),
    nombre character varying(255),
    posicion character varying(255)
);


ALTER TABLE public.jugador OWNER TO postgres;

--
-- TOC entry 286 (class 1259 OID 18314)
-- Name: jugador_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.jugador ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jugador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 289 (class 1259 OID 18323)
-- Name: partido; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.partido (
    fecha date,
    goles_local integer NOT NULL,
    goles_visita integer NOT NULL,
    equipo_local bigint NOT NULL,
    equipo_visita bigint NOT NULL,
    id bigint NOT NULL,
    estadio character varying(255)
);


ALTER TABLE public.partido OWNER TO postgres;

--
-- TOC entry 288 (class 1259 OID 18322)
-- Name: partido_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.partido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3831 (class 0 OID 18293)
-- Dependencies: 281
-- Data for Name: entrenador; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.entrenador (equipo_id, id, especialidad, nombre) FROM stdin;
1	1	Principal	Juan Martínez
2	2	Asistente	Pedro Gómez
3	3	Principal	Carlos Díaz
4	4	Asistente	Luis Suárez
5	5	Principal	Andrés Silva
6	6	Preparador físico	Daniel Salgado
7	7	Asistente	Nicolás Restrepo
8	8	Principal	Oscar Jiménez
9	9	Analista táctico	Henry Beltrán
10	10	Principal	Víctor Ruiz
\.


--
-- TOC entry 3833 (class 0 OID 18301)
-- Dependencies: 283
-- Data for Name: equipo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.equipo (fundacion, id, ciudad, nombre) FROM stdin;
2001-03-10	1	Bogotá	Tigres FC
2001-03-10	2	Bogotá	Tigres FC
1962-08-15	3	Cali	Deportivo Cali
1924-08-07	4	Barranquilla	Junior FC
1941-02-28	5	Bogotá	Santa Fe
1947-06-12	6	Medellín	Nacional
1946-06-18	7	Bogotá	Millonarios
1961-04-05	8	Manizales	Once Caldas
1989-07-01	9	Envigado	Envigado FC
2003-03-01	10	Tunja	Patriotas
\.


--
-- TOC entry 3835 (class 0 OID 18309)
-- Dependencies: 285
-- Data for Name: estadisticas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.estadisticas (asistencias, goles, minutos_jugados, tarjetas_amarillas, tarjetas_rojas, id, id_jugador, id_partido) FROM stdin;
0	1	90	0	0	1	1	1
1	1	85	1	0	2	2	1
0	1	90	1	0	3	3	2
0	0	90	0	0	4	4	3
1	0	90	2	0	5	5	4
1	2	90	0	0	6	6	5
2	0	90	1	0	7	7	6
1	1	90	0	1	8	8	7
0	0	90	1	1	9	9	8
0	1	90	0	0	10	10	9
\.


--
-- TOC entry 3837 (class 0 OID 18315)
-- Dependencies: 287
-- Data for Name: jugador; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.jugador (dorsal, fecha_nac, equipo_id, id, nacionalidad, nombre, posicion) FROM stdin;
10	1996-02-28	1	2	Colombiana	Luis Pérez	Mediocampista
4	1994-09-14	2	3	Colombiana	Andrés Ríos	Defensa
1	1990-06-22	3	4	Colombiana	Santiago Mejía	Portero
3	1997-12-01	4	5	Colombiana	Johan Torres	Defensa
8	1995-10-09	5	6	Colombiana	David Pineda	Mediocampista
7	1999-01-18	6	7	Colombiana	Mateo Suárez	Delantero
11	2000-11-30	7	8	Colombiana	Cristian León	Delantero
5	1993-03-11	8	9	Colombiana	Sebastián López	Defensa
6	1998-04-27	9	10	Colombiana	Kevin Vargas	Mediocampista
10	1998-05-12	1	1	Colombiana	Carlos Rodríguez	Delantero
\.


--
-- TOC entry 3839 (class 0 OID 18323)
-- Dependencies: 289
-- Data for Name: partido; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.partido (fecha, goles_local, goles_visita, equipo_local, equipo_visita, id, estadio) FROM stdin;
2024-03-15	2	1	1	2	1	El Campín
2024-03-20	3	2	3	4	2	Atanasio
2024-03-25	1	0	5	6	3	Metropolitano
2024-03-30	0	2	7	8	4	Nemesio Camacho
2024-04-02	2	2	9	10	5	Palogrande
2024-04-05	1	3	1	3	6	El Campín
2024-04-10	0	1	2	5	7	Atanasio
2024-04-15	2	2	4	6	8	Metropolitano
2024-04-20	1	1	7	10	9	Nemesio Camacho
2024-04-25	0	0	8	9	10	Palogrande
\.


--
-- TOC entry 3857 (class 0 OID 0)
-- Dependencies: 280
-- Name: entrenador_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.entrenador_id_seq', 1, false);


--
-- TOC entry 3858 (class 0 OID 0)
-- Dependencies: 282
-- Name: equipo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.equipo_id_seq', 2, true);


--
-- TOC entry 3859 (class 0 OID 0)
-- Dependencies: 284
-- Name: estadisticas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.estadisticas_id_seq', 1, false);


--
-- TOC entry 3860 (class 0 OID 0)
-- Dependencies: 286
-- Name: jugador_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.jugador_id_seq', 1, false);


--
-- TOC entry 3861 (class 0 OID 0)
-- Dependencies: 288
-- Name: partido_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.partido_id_seq', 1, false);


--
-- TOC entry 3665 (class 2606 OID 18299)
-- Name: entrenador entrenador_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.entrenador
    ADD CONSTRAINT entrenador_pkey PRIMARY KEY (id);


--
-- TOC entry 3667 (class 2606 OID 18307)
-- Name: equipo equipo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipo
    ADD CONSTRAINT equipo_pkey PRIMARY KEY (id);


--
-- TOC entry 3669 (class 2606 OID 18313)
-- Name: estadisticas estadisticas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estadisticas
    ADD CONSTRAINT estadisticas_pkey PRIMARY KEY (id);


--
-- TOC entry 3671 (class 2606 OID 18321)
-- Name: jugador jugador_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jugador
    ADD CONSTRAINT jugador_pkey PRIMARY KEY (id);


--
-- TOC entry 3673 (class 2606 OID 18327)
-- Name: partido partido_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partido
    ADD CONSTRAINT partido_pkey PRIMARY KEY (id);


--
-- TOC entry 3678 (class 2606 OID 18348)
-- Name: partido fk1q3nbh68hi4xmjtvh8kp65mw1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partido
    ADD CONSTRAINT fk1q3nbh68hi4xmjtvh8kp65mw1 FOREIGN KEY (equipo_local) REFERENCES public.equipo(id);


--
-- TOC entry 3674 (class 2606 OID 18328)
-- Name: entrenador fkc9kltfpcqcu1nn0uwjecqeba7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.entrenador
    ADD CONSTRAINT fkc9kltfpcqcu1nn0uwjecqeba7 FOREIGN KEY (equipo_id) REFERENCES public.equipo(id);


--
-- TOC entry 3677 (class 2606 OID 18343)
-- Name: jugador fkcc4h4wqekf4kicyifbrit5sp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jugador
    ADD CONSTRAINT fkcc4h4wqekf4kicyifbrit5sp FOREIGN KEY (equipo_id) REFERENCES public.equipo(id);


--
-- TOC entry 3675 (class 2606 OID 18333)
-- Name: estadisticas fkhaybd37yry9fs82nbu84augnw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estadisticas
    ADD CONSTRAINT fkhaybd37yry9fs82nbu84augnw FOREIGN KEY (id_jugador) REFERENCES public.jugador(id);


--
-- TOC entry 3679 (class 2606 OID 18353)
-- Name: partido fkp3l4xr7d0ieyxxk9gp6iyo4sj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partido
    ADD CONSTRAINT fkp3l4xr7d0ieyxxk9gp6iyo4sj FOREIGN KEY (equipo_visita) REFERENCES public.equipo(id);


--
-- TOC entry 3676 (class 2606 OID 18338)
-- Name: estadisticas fkukkjnn5xe60wds5oeep2qjcu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estadisticas
    ADD CONSTRAINT fkukkjnn5xe60wds5oeep2qjcu FOREIGN KEY (id_partido) REFERENCES public.partido(id);


--
-- TOC entry 3846 (class 0 OID 0)
-- Dependencies: 23
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;


--
-- TOC entry 3847 (class 0 OID 0)
-- Dependencies: 281
-- Name: TABLE entrenador; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.entrenador TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.entrenador TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.entrenador TO service_role;


--
-- TOC entry 3848 (class 0 OID 0)
-- Dependencies: 280
-- Name: SEQUENCE entrenador_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.entrenador_id_seq TO anon;
GRANT ALL ON SEQUENCE public.entrenador_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.entrenador_id_seq TO service_role;


--
-- TOC entry 3849 (class 0 OID 0)
-- Dependencies: 283
-- Name: TABLE equipo; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.equipo TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.equipo TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.equipo TO service_role;


--
-- TOC entry 3850 (class 0 OID 0)
-- Dependencies: 282
-- Name: SEQUENCE equipo_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.equipo_id_seq TO anon;
GRANT ALL ON SEQUENCE public.equipo_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.equipo_id_seq TO service_role;


--
-- TOC entry 3851 (class 0 OID 0)
-- Dependencies: 285
-- Name: TABLE estadisticas; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.estadisticas TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.estadisticas TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.estadisticas TO service_role;


--
-- TOC entry 3852 (class 0 OID 0)
-- Dependencies: 284
-- Name: SEQUENCE estadisticas_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.estadisticas_id_seq TO anon;
GRANT ALL ON SEQUENCE public.estadisticas_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.estadisticas_id_seq TO service_role;


--
-- TOC entry 3853 (class 0 OID 0)
-- Dependencies: 287
-- Name: TABLE jugador; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.jugador TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.jugador TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.jugador TO service_role;


--
-- TOC entry 3854 (class 0 OID 0)
-- Dependencies: 286
-- Name: SEQUENCE jugador_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.jugador_id_seq TO anon;
GRANT ALL ON SEQUENCE public.jugador_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.jugador_id_seq TO service_role;


--
-- TOC entry 3855 (class 0 OID 0)
-- Dependencies: 289
-- Name: TABLE partido; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.partido TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.partido TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.partido TO service_role;


--
-- TOC entry 3856 (class 0 OID 0)
-- Dependencies: 288
-- Name: SEQUENCE partido_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.partido_id_seq TO anon;
GRANT ALL ON SEQUENCE public.partido_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.partido_id_seq TO service_role;


--
-- TOC entry 2476 (class 826 OID 18158)
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- TOC entry 2479 (class 826 OID 18159)
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- TOC entry 2481 (class 826 OID 18160)
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- TOC entry 2482 (class 826 OID 18161)
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- TOC entry 2483 (class 826 OID 18162)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO service_role;


--
-- TOC entry 2485 (class 826 OID 18163)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO service_role;


-- Completed on 2025-04-22 18:46:11

--
-- PostgreSQL database dump complete
--

